id: PF45686FD
initial_creation_type: ocr
source_metadata:
  volumes:
    db84a218eddc4b1c8d9b1c7641fd3851:
      base_file: v039.txt
      image_group_id: I1PD95884
      title: སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1625
      volume_number: 39
